### ISSUE TITLE
Getting hit with internal server error

### ISSUE THREAD

**Issue by iJigg** [goabstract/abstract-sdk#218]
Running abstract-sdk and trying to ```assets.file({ projectId, fileId, branchId, sha })``` being hit with InternalServerError and have no way of debugging further.

```
MultiError: An error has occured
    at makeRequest (path/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:89:15)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  name: 'MultiError',
  errors: {
    api: InternalServerError: Internal server error.
        at throwAPIError (path/node_modules/abstract-sdk/dist/errors.js:201:13)
        at Assets.apiRequest (path/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:113:54)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at async makeRequest (path/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:76:22)
        at async AbstractAPI.listAssetsForFile (path/src/abstract.js:142:19)
        at async abstractMain (path/index.js:48:19) {
      name: 'InternalServerError',
```

**Comment by bitpshr** [comment]
Hi @iJigg, thanks for reaching out. Note that you can always catch an SDK error and log it to to the console for more information. Specifically, check the `Error` object's `errors` property, which will contain references to any transport errors that occurred during execution.

**Comment by tommoor** [comment]
@iJigg if you email with your abstract username then we can try and track down the error on the backend (tom / paul @abstract.com)

**Comment by davetakahashi-abstract** [comment]
@iJigg We have deployed a fix that should address this error. If you would like to try it now and let us know, that would be excellent. Thanks!

**Comment by tommoor** [comment]
Counting this as resolved as the fix was deployed and we never heard back.

**Comment by iJigg** [comment]
Seems to be working now, thanks! ✨
