### ISSUE TITLE
ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by mascardoso** [goabstract/abstract-sdk#262]
I'm getting this recently on the latest `beta-26`

```
MultiError: An error has occured
    at _callee$ (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:248:25)
    at tryCatch (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:70:103)
    at _next (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:72:194)
    at /Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:72:364
    at new Promise (<anonymous>)
    at /Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:72:97
    at makeRequest (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:262:23) {
  name: 'MultiError',
  errors: {
    api: ReferenceError: performance is not defined
        at _callee$ (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:164:19)
        at tryCatch (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/regenerator-runtime/runtime.js:274:22)
        at Generator.prototype.<computed> [as next] (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/regenerator-runtime/runtime.js:97:21)
        at asyncGeneratorStep (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:70:103)
        at _next (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:72:194)
        at /Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:72:364
        at new Promise (<anonymous>)
        at /Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:72:97
        at makeRequest (/Users/cardomar/Web/uxf-adl-abstract-tf/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:262:23)
  }
}
```

Thanks.

**Comment by mascardoso** [comment]
Just saw this https://github.com/goabstract/abstract-sdk/pull/258
Apologies.
Will close. When will you be able to release the latest?
