### ISSUE TITLE
### `\abstract-sdk\dist\endpoints\Endpoint.js` can not find` abstract-cli.exe `in Windows 10 64bit

### ISSUE THREAD

**Issue by hiteshsahu** [goabstract/abstract-sdk#311]
### `\abstract-sdk\dist\endpoints\Endpoint.js` can not find` abstract-cli.exe `in Windows 10 64bit

DEV ENVIRONEMNT 
![image](https://user-images.githubusercontent.com/4076925/95071672-590ca380-070a-11eb-83e4-adbda3633880.png)

LOGS
```
Error: abstract-cli.exe could not be accessed at the expected path: C:\Users\HiteshKumarSahu\Documents\WorkSpace\AbstractClient\server\node_modules\@elasticprojects\abstract-cli\bin\abstract-cli.exe
    at resolveCLIBinary (C:\Users\HiteshKumarSahu\Documents\WorkSpace\AbstractClient\server\node_modules\@elasticprojects\abstract-cli\index.js:20:13)
    at Object.<anonymous> (C:\Users\HiteshKumarSahu\Documents\WorkSpace\AbstractClient\server\node_modules\@elasticprojects\abstract-cli\index.js:30:18)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\HiteshKumarSahu\Documents\WorkSpace\AbstractClient\server\node_modules\abstract-sdk\dist\endpoints\Endpoint.js:96:15)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `npm run build && node dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HiteshKumarSahu\AppData\Roaming\npm-cache\_logs\2020-10-05T10_54_14_743Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 restart: `rimraf dist && npm run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 restart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HiteshKumarSahu\AppData\Roaming\npm-cache\_logs\2020-10-05T10_54_14_841Z-debug.l

![image](https://user-images.githubusercontent.com/4076925/95071490-08954600-070a-11eb-921d-844461de9d31.png)

```

**Comment by tommoor** [comment]
Hi, at this time we're not supporting the CLI transport on Windows. It's only supported on Mac, where our desktop application runs.

You should be able to explicitly set the [transport mode](https://sdk.abstract.com/docs/configuration/#transportmode) to `api` though to load data only from our API on Windows.

**Comment by JSMike** [comment]
@tommoor explicitly setting transportMode: ['api'] is currently not working in windows, it's still throwing an error failing to find abstract-cli.exe
